CREATE DATABASE bookrestapi;
USE bookRestApi;
CREATE TABLE book (
  id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  author VARCHAR(500) NOT NULL,
  title VARCHAR(5000) NOT NULL,
  description VARCHAR(5000) NOT NULL
);